@demo
Feature: W3 demo command — the spec-conformance matrix cannot lie
  bin/otto-demo is the one command that replays the Otto evidence set
  fresh and prints a matrix mapping every spec section to the tests that
  prove it (spec docs/specs/otto-platform-v1/OBSERVABILITY-DEMO-ONBOARDING.md,
  W3, crew#768). These scenarios prove the command's own honesty: a green
  head exits 0 with an all-green matrix and a regenerated page, a spec
  section with no covering tests is a red row and a nonzero exit (the
  cannot-lie-by-omission proof), a failing test is a nonzero exit, and a
  test file no section claims is itself a red row.

  Each scenario drives the real executable in a subprocess, pointed at a
  small fixture manifest so a laptop run finishes in seconds; the
  committed docs/demo/otto.md is regenerated by running the command with
  no overrides at all.

  Scenario: A green head exits 0 with an all-green matrix and regenerates the page
    Given a manifest whose one section is proved by the real assembly tests
    When the demo command runs
    Then it exits with code 0
    And every matrix row is green and none is red
    And the generated page exists with the do-not-edit header and a UTC timestamp

  Scenario: A section with no covering tests is a red row and a nonzero exit
    Given a manifest whose one section points at a directory with no tests
    When the demo command runs
    Then it exits with a nonzero code
    And the matrix shows a red row saying no tests cover the section
    And the generated page records the red row

  Scenario: A failing test makes the demo exit nonzero
    Given a manifest whose one section points at a directory with a failing test
    When the demo command runs
    Then it exits with a nonzero code
    And the matrix shows a red row with a failure count

  Scenario: A test file no section claims is itself a red row
    Given a manifest that claims one directory while a stray test file sits beside it
    When the demo command runs
    Then it exits with a nonzero code
    And the matrix shows a red row for the unclaimed test file
