"""Step definitions for ``features/w3_demo_command.feature``.

Each scenario runs the real ``bin/otto-demo`` executable in a
subprocess against a small fixture manifest (via the two environment
variables the command exposes for exactly this suite), so what is
graded is the shipped command end to end: manifest loading, the fresh
pytest run, the matrix, the generated page and the exit code.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from pytest_bdd import given, scenarios, then, when

scenarios("../features/w3_demo_command.feature")

# step_defs/ -> demo/ -> tests/ -> otto/ -> repository root (LAW 46:
# derived from this file's own location, never typed as a literal).
REPO_ROOT = Path(__file__).resolve().parents[4]
DEMO_COMMAND = REPO_ROOT / "bin" / "otto-demo"

DO_NOT_EDIT_HEADER = "generated by bin/otto-demo, do not edit"


def _write_manifest(tmp_path: Path, sections: list[dict], suite_root: str) -> Path:
    manifest_path = tmp_path / "manifest.json"
    manifest_path.write_text(
        json.dumps({"suite_root": suite_root, "sections": sections}),
        encoding="utf-8",
    )
    return manifest_path


# -- given -------------------------------------------------------------------


@given("a manifest whose one section is proved by the real assembly tests")
def manifest_green(ctx: dict, tmp_path: Path) -> None:
    ctx["manifest"] = _write_manifest(
        tmp_path,
        [
            {
                "section": "Assembly (one task end to end)",
                "claim": "One task crosses all six lanes in a single process.",
                "path": "otto/tests/integration",
            }
        ],
        suite_root="otto/tests/integration",
    )
    ctx["output"] = tmp_path / "otto.md"


@given("a manifest whose one section points at a directory with no tests")
def manifest_empty_dir(ctx: dict, tmp_path: Path) -> None:
    empty = tmp_path / "no_tests_here"
    empty.mkdir()
    ctx["manifest"] = _write_manifest(
        tmp_path,
        [
            {
                "section": "CP4 memory",
                "claim": "Facts carry provenance and survive restarts.",
                "path": str(empty),
            }
        ],
        suite_root=str(empty),
    )
    ctx["output"] = tmp_path / "otto.md"


@given("a manifest whose one section points at a directory with a failing test")
def manifest_failing(ctx: dict, tmp_path: Path) -> None:
    failing_dir = tmp_path / "failing_suite"
    failing_dir.mkdir()
    (failing_dir / "test_always_red.py").write_text(
        "def test_always_red():\n"
        '    raise AssertionError("this fixture test fails on purpose")\n',
        encoding="utf-8",
    )
    ctx["manifest"] = _write_manifest(
        tmp_path,
        [
            {
                "section": "CP3 verify",
                "claim": "Work is claimed and gated on a signed verdict.",
                "path": str(failing_dir),
            }
        ],
        suite_root=str(failing_dir),
    )
    ctx["output"] = tmp_path / "otto.md"


@given("a manifest that claims one directory while a stray test file sits beside it")
def manifest_stray(ctx: dict, tmp_path: Path) -> None:
    suite_root = tmp_path / "suite"
    claimed = suite_root / "claimed"
    claimed.mkdir(parents=True)
    (claimed / "test_claimed_green.py").write_text(
        "def test_claimed_green():\n    assert True\n", encoding="utf-8"
    )
    (suite_root / "test_stray_orphan.py").write_text(
        "def test_stray_orphan():\n    assert True\n", encoding="utf-8"
    )
    ctx["manifest"] = _write_manifest(
        tmp_path,
        [
            {
                "section": "CP1 spine",
                "claim": "One task envelope and a durable bus.",
                "path": str(claimed),
            }
        ],
        suite_root=str(suite_root),
    )
    ctx["output"] = tmp_path / "otto.md"


# -- when --------------------------------------------------------------------


@when("the demo command runs")
def run_demo(ctx: dict) -> None:
    env = dict(os.environ)
    env["OTTO_DEMO_MANIFEST"] = str(ctx["manifest"])
    env["OTTO_DEMO_OUTPUT"] = str(ctx["output"])
    result = subprocess.run(
        [sys.executable, str(DEMO_COMMAND)],
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=600,
    )
    ctx["result"] = result
    ctx["stdout"] = result.stdout + result.stderr


# -- then --------------------------------------------------------------------


@then("it exits with code 0")
def exits_zero(ctx: dict) -> None:
    assert ctx["result"].returncode == 0, ctx["stdout"]


@then("it exits with a nonzero code")
def exits_nonzero(ctx: dict) -> None:
    assert ctx["result"].returncode != 0, ctx["stdout"]


@then("every matrix row is green and none is red")
def all_rows_green(ctx: dict) -> None:
    assert "GREEN - all" in ctx["stdout"], ctx["stdout"]
    assert "RED -" not in ctx["stdout"], ctx["stdout"]


@then("the generated page exists with the do-not-edit header and a UTC timestamp")
def page_generated(ctx: dict) -> None:
    page = ctx["output"].read_text(encoding="utf-8")
    assert DO_NOT_EDIT_HEADER in page, page
    # The ISO UTC stamp always carries the +00:00 offset.
    assert "+00:00" in page, page


@then("the matrix shows a red row saying no tests cover the section")
def red_row_no_tests(ctx: dict) -> None:
    assert "RED - no tests cover this section" in ctx["stdout"], ctx["stdout"]


@then("the generated page records the red row")
def page_records_red(ctx: dict) -> None:
    page = ctx["output"].read_text(encoding="utf-8")
    assert "RED -" in page, page
    assert "NOT PROVEN" in page, page


@then("the matrix shows a red row with a failure count")
def red_row_failure_count(ctx: dict) -> None:
    assert "RED - 1 failed" in ctx["stdout"], ctx["stdout"]


@then("the matrix shows a red row for the unclaimed test file")
def red_row_unclaimed(ctx: dict) -> None:
    assert "RED - no spec section claims this test file" in ctx["stdout"], ctx["stdout"]
    assert "test_stray_orphan.py" in ctx["stdout"], ctx["stdout"]
